insert into CAT(PET_ID, NAME,TYPE , OWNER_NAME, ADDRESS, AGE, IS_SPRAYED,BIRTHDATE)
VALUES (101,'NIGEL','WHITE','STAJE', '101 TILTED TOWER ROAD', '5', true, 'June 7th');
insert into CAT(PET_ID, NAME,TYPE , OWNER_NAME, ADDRESS, AGE, IS_SPRAYED,BIRTHDATE)
VALUES (102,'EGORE','BLACK','STAJE', '105 TILTED TOWER ROAD', '6', true, 'MAY 7th');